# Generated by Django 2.2.1 on 2019-12-02 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tripvisor', '0002_add_tour_name_Tour'),
    ]

    operations = [
        migrations.AddField(
            model_name='attraction',
            name='image',
            field=models.ImageField(blank=True, upload_to='attraction_image'),
        ),
    ]
